FROM python:3.10-slim

WORKDIR /rag_model

COPY requirements.txt /rag_model/requirements.txt

RUN pip install --no-cache-dir -r /rag_model/requirements.txt

COPY . /rag_model

EXPOSE 8000

CMD ["python", "main.py"]